version: '3'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "dbpassword"
    env_file:
      - variable.env
    volumes:
          - ./script.sh:/docker-entrypoint-initdb.d/script.sh
  api:
    build:
      context: "./backend/."
      args:
        JAR_FILE: "/target/spring-boot-blog-api.jar"
    env_file:
      - variable.env
    ports:
      - "8080:8080"
  frontend:
    build:
      context: "./frontend/."
    ports:
      - "80:80"
